/* 
 * Chroma Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace CustomChromaSDK.CustomChromaPackage.Model
{
    /// <summary>
    /// Chroma generic effects. Note that not all devices supported the listed effects
    /// </summary>
    /// <value>Chroma generic effects. Note that not all devices supported the listed effects</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EffectType
    {
        
        /// <summary>
        /// Enum CHROMA_NONE
        /// </summary>
        [EnumMember(Value = "CHROMA_NONE")]
        CHROMA_NONE,
        
        /// <summary>
        /// Enum CHROMA_WAVE
        /// </summary>
        [EnumMember(Value = "CHROMA_WAVE")]
        CHROMA_WAVE,
        
        /// <summary>
        /// Enum CHROMA_SPECTRUMCYCLING
        /// </summary>
        [EnumMember(Value = "CHROMA_SPECTRUMCYCLING")]
        CHROMA_SPECTRUMCYCLING,
        
        /// <summary>
        /// Enum CHROMA_BREATHING
        /// </summary>
        [EnumMember(Value = "CHROMA_BREATHING")]
        CHROMA_BREATHING,
        
        /// <summary>
        /// Enum CHROMA_BLINKING
        /// </summary>
        [EnumMember(Value = "CHROMA_BLINKING")]
        CHROMA_BLINKING,
        
        /// <summary>
        /// Enum CHROMA_REACTIVE
        /// </summary>
        [EnumMember(Value = "CHROMA_REACTIVE")]
        CHROMA_REACTIVE,
        
        /// <summary>
        /// Enum CHROMA_STATIC
        /// </summary>
        [EnumMember(Value = "CHROMA_STATIC")]
        CHROMA_STATIC,
        
        /// <summary>
        /// Enum CHROMA_CUSTOM
        /// </summary>
        [EnumMember(Value = "CHROMA_CUSTOM")]
        CHROMA_CUSTOM,
        
        /// <summary>
        /// Enum CHROMA_RESERVED
        /// </summary>
        [EnumMember(Value = "CHROMA_RESERVED")]
        CHROMA_RESERVED,
        
        /// <summary>
        /// Enum CHROMA_INVALID
        /// </summary>
        [EnumMember(Value = "CHROMA_INVALID")]
        CHROMA_INVALID
    }

}
