/* 
 * Chroma Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.chromasdk.model
{
    /// <summary>
    /// Chroma generic effects. Note that not all devices supported the listed effects
    /// </summary>
    /// <value>Chroma generic effects. Note that not all devices supported the listed effects</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EffectType
    {
        /// <summary>
        /// Enum WAVE for "CHROMA_NONE"
        /// </summary>
        [EnumMember(Value = "CHROMA_NONE")]
        CHROMA_NONE,

        /// <summary>
        /// Enum WAVE for "CHROMA_WAVE"
        /// </summary>
        [EnumMember(Value = "CHROMA_WAVE")]
        CHROMA_WAVE,

        /// <summary>
        /// Enum SPECTRUMCYCLING for "CHROMA_SPECTRUMCYCLING"
        /// </summary>
        [EnumMember(Value = "CHROMA_SPECTRUMCYCLING")]
        CHROMA_SPECTRUMCYCLING,

        /// <summary>
        /// Enum BREATHING for "CHROMA_BREATHING"
        /// </summary>
        [EnumMember(Value = "CHROMA_BREATHING")]
        CHROMA_BREATHING,

        /// <summary>
        /// Enum BLINKING for "CHROMA_BLINKING"
        /// </summary>
        [EnumMember(Value = "CHROMA_BLINKING")]
        CHROMA_BLINKING,

        /// <summary>
        /// Enum REACTIVE for "CHROMA_REACTIVE"
        /// </summary>
        [EnumMember(Value = "CHROMA_REACTIVE")]
        CHROMA_REACTIVE,

        /// <summary>
        /// Enum STATIC for "CHROMA_STATIC"
        /// </summary>
        [EnumMember(Value = "CHROMA_STATIC")]
        CHROMA_STATIC,

        /// <summary>
        /// Enum CUSTOM for "CHROMA_CUSTOM"
        /// </summary>
        [EnumMember(Value = "CHROMA_CUSTOM")]
        CHROMA_CUSTOM,

        /// <summary>
        /// Enum RESERVED for "CHROMA_RESERVED"
        /// </summary>
        [EnumMember(Value = "CHROMA_RESERVED")]
        CHROMA_RESERVED,

        /// <summary>
        /// Enum INVALID for "CHROMA_INVALID"
        /// </summary>
        [EnumMember(Value = "CHROMA_INVALID")]
        CHROMA_INVALID
    }

}
